### ISSUE TITLE
Can Dotterel identify as external keyboard

### ISSUE THREAD

**Issue by zenmetsu** [nimble0/dotterel#31]
Hello!

I realized that attempting to use certain programs, such as Discord, results in unexpected behavior when sending Enter.  These apps are configured to send SHIFT-ENTER when an on-screen keyboard is used so as to permit a user to enter multi-line text, after which the message is sent via a button on-screen.

Unfortunately, this behaviour is highly disruptive.  One can bind R-R to `return` and R*R to `shift-return`, but as long as Dotterel presents itself as an on-screen input device, these apps will treat return differently.

Is this something that can be changed, possibly as a toggle within the configs?

**Comment by nimble0** [comment]
I don't quite understand what you mean. Can you express this in the form:
- Action(s)
- Expected behaviour
- Actual behaviour

I don't think Android has any concept of an external keyboard IME. There is an `IME:EDITOR_ACTION` command described here https://github.com/nimble0/dotterel/wiki/Dotterel-commands which might be of use to you.

**Comment by zenmetsu** [comment]
I will close this as it is invalid.  It turns out that the applications that I am attempting to use are treating both hardware devices and software identically.
